movies_list = [
    {"id": 1, "title": "Inception", "year": 2010,
        "overview": "A skilled thief is given a chance to erase his criminal record by performing an impossible task.", "category": "Sci-Fi", "rating": 8.8},
    {"id": 2, "title": "The Dark Knight", "year": 2008,
        "overview": "Batman faces the Joker, a criminal mastermind who seeks to create chaos in Gotham City.", "category": "Action", "rating": 9.0},
    {"id": 3, "title": "The Godfather", "year": 1972,
        "overview": "The aging patriarch of an organized crime dynasty transfers control of his empire to his son.", "category": "Crime", "rating": 9.2},
    {"id": 4, "title": "Pulp Fiction", "year": 1994,
        "overview": "The lives of two mob hitmen, a boxer, and others intertwine in a series of criminal activities.", "category": "Crime", "rating": 8.9},
    {"id": 5, "title": "The Lord of the Rings: The Fellowship of the Ring", "year": 2001,
        "overview": "A young hobbit embarks on a dangerous journey to destroy a powerful ring.", "category": "Fantasy", "rating": 8.8},
    {"id": 6, "title": "The Matrix", "year": 1999,
        "overview": "A computer hacker learns about the true nature of his reality and his role in the war against its controllers.", "category": "Sci-Fi", "rating": 8.7},
    {"id": 7, "title": "Forrest Gump", "year": 1994,
        "overview": "The story of a man with a low IQ who achieves remarkable things in life.", "category": "Drama", "rating": 8.8},
    {"id": 8, "title": "Schindler's List", "year": 1993,
        "overview": "In Nazi Germany, a businessman works to save the lives of Jewish refugees.", "category": "History", "rating": 9.0},
    {"id": 9, "title": "The Avengers", "year": 2012,
        "overview": "Earth's mightiest heroes come together to fight a powerful enemy.", "category": "Action", "rating": 8.0},
    {"id": 10, "title": "Titanic", "year": 1997,
        "overview": "A romance blossoms aboard the doomed RMS Titanic.", "category": "Romance", "rating": 7.8},
    {"id": 11, "title": "Fight Club", "year": 1999,
        "overview": "An insomniac office worker forms an underground fight club as a form of escapism.", "category": "Drama", "rating": 8.8},
    {"id": 12, "title": "Gladiator", "year": 2000,
        "overview": "A Roman general seeks revenge after being betrayed and losing his family.", "category": "Action", "rating": 8.5},
    {"id": 13, "title": "Saving Private Ryan", "year": 1998,
        "overview": "A group of soldiers is sent to find a missing paratrooper during WWII.", "category": "War", "rating": 8.6},
    {"id": 14, "title": "The Lion King", "year": 1994,
        "overview": "A lion cub flees after his father's death, only to learn the importance of his place in the kingdom.", "category": "Animation", "rating": 8.5},
    {"id": 15, "title": "Interstellar", "year": 2014,
        "overview": "A team of explorers travels through a wormhole in search of a new home for humanity.", "category": "Sci-Fi", "rating": 8.6},
    {"id": 16, "title": "Parasite", "year": 2019,
        "overview": "A poor family schemes to become employed by a wealthy family.", "category": "Thriller", "rating": 8.6},
    {"id": 17, "title": "The Shawshank Redemption", "year": 1994,
        "overview": "A man imprisoned for murder forms an unlikely friendship while trying to prove his innocence.", "category": "Drama", "rating": 9.3},
    {"id": 18, "title": "Star Wars: A New Hope", "year": 1977,
        "overview": "A young man joins a rebellion to fight against an oppressive empire.", "category": "Sci-Fi", "rating": 8.6},
    {"id": 19, "title": "Jurassic Park", "year": 1993,
        "overview": "A theme park is thrown into chaos when cloned dinosaurs escape.", "category": "Adventure", "rating": 8.1},
    {"id": 20, "title": "Avengers: Endgame", "year": 2019,
        "overview": "The Avengers assemble one last time to undo the destruction caused by Thanos.", "category": "Action", "rating": 8.4},
    {"id": 21, "title": "The Silence of the Lambs", "year": 1991,
        "overview": "A young FBI agent seeks the help of a cannibalistic serial killer to catch another serial killer.", "category": "Thriller", "rating": 8.6},
    {"id": 22, "title": "Goodfellas", "year": 1990,
        "overview": "The rise and fall of a gangster in the mob underworld.", "category": "Crime", "rating": 8.7},
    {"id": 23, "title": "Braveheart", "year": 1995,
        "overview": "Scottish warrior William Wallace leads a revolt against English rule.", "category": "History", "rating": 8.3},
    {"id": 24, "title": "Coco", "year": 2017, "overview": "A young boy ventures into the Land of the Dead to discover his family's legacy.",
        "category": "Animation", "rating": 8.4},
    {"id": 25, "title": "Black Panther", "year": 2018,
        "overview": "T'Challa, the king of Wakanda, must defend his kingdom from a powerful enemy.", "category": "Action", "rating": 7.3},
    {"id": 26, "title": "La La Land", "year": 2016,
        "overview": "A musician and an aspiring actress navigate love and ambition in Los Angeles.", "category": "Romance", "rating": 8.0},
    {"id": 27, "title": "Joker", "year": 2019,
        "overview": "An aspiring stand-up comedian spirals into madness and becomes a symbol of chaos.", "category": "Thriller", "rating": 8.5},
    {"id": 28, "title": "The Social Network", "year": 2010,
        "overview": "The story of the founding of Facebook and the legal battles that followed.", "category": "Drama", "rating": 7.7},
    {"id": 29, "title": "The Wolf of Wall Street", "year": 2013,
        "overview": "The rise and fall of a corrupt stockbroker during the 1990s.", "category": "Comedy", "rating": 8.2},
    {"id": 30, "title": "Toy Story", "year": 1995,
        "overview": "A group of toys comes to life when their owner is not around.", "category": "Animation", "rating": 8.3},
    {"id": 31, "title": "Finding Nemo", "year": 2003,
        "overview": "A clownfish embarks on a journey to find his son.", "category": "Animation", "rating": 8.1},
    {"id": 32, "title": "Shutter Island", "year": 2010,
        "overview": "Two U.S. Marshals investigate a psychiatric facility for the criminally insane.", "category": "Thriller", "rating": 8.2},
    {"id": 33, "title": "The Grand Budapest Hotel", "year": 2014,
        "overview": "The adventures of a concierge and his lobby boy in a famous European hotel.", "category": "Comedy", "rating": 8.1},
    {"id": 34, "title": "Django Unchained", "year": 2012,
        "overview": "A freed slave sets out to rescue his wife from a brutal plantation owner.", "category": "Western", "rating": 8.4},
    {"id": 35, "title": "Blade Runner 2049", "year": 2017,
        "overview": "A young blade runner unearths a secret that could plunge society into chaos.", "category": "Sci-Fi", "rating": 8.0},
    {"id": 36, "title": "The Departed", "year": 2006,
        "overview": "An undercover cop and a mole in the police attempt to identify each other.", "category": "Crime", "rating": 8.5},
    {"id": 37, "title": "Whiplash", "year": 2014,
        "overview": "A young drummer struggles under the guidance of a ruthless instructor.", "category": "Drama", "rating": 8.5},
    {"id": 38, "title": "No Country for Old Men", "year": 2007,
        "overview": "A hunter stumbles upon a drug deal gone wrong and becomes a target.", "category": "Thriller", "rating": 8.1},
    {"id": 39, "title": "The Prestige", "year": 2006,
        "overview": "Two magicians engage in a deadly rivalry.", "category": "Thriller", "rating": 8.5},
    {"id": 40, "title": "Mad Max: Fury Road", "year": 2015,
        "overview": "In a post-apocalyptic world, a drifter and a group of rebels fight for survival.", "category": "Action", "rating": 8.1},
]

categories = [
    "Sci-Fi", "Action", "Crime", "Fantasy", "Drama", "History", "Romance",
    "War", "Animation", "Thriller", "Adventure", "Comedy", "Western"
]
